### ISSUE TITLE
Crash on project open

### ISSUE THREAD

**Issue by kohtenko** [AlexIzh/TimePlugin#1]
Using Xcode 6.3.1 (6D1002). Plugins installed via Alcatraz.

**Comment by AlexIzh** [comment]
Are you sure that this happened because this plugin ?

**Comment by kohtenko** [comment]
Wow) I think after almost year past and Xcode updated to 7.1 this issue is not actual anymore :) 
BTW. As far as I see, plugins usually updated almost with every Xcode release.

**Comment by AlexIzh** [comment]
Usually yes, but this plugin is not popular, unfortunately.
